---
  - hosts:  slave1
    become: true
    name: Play1
    sudo: yes
    tasks:
      - name: execute script on the server
        script: script1.sh
      - name: Install ngnix
        apt: name=nginx state=latest
  - hosts:  slave2
    become: true
    name: Play2
    sudo: yes
    tasks:
      - name: execute script on the server
        script: script2.sh
      - name: Install apache2
        apt: name=apache2 state=latest
